@hostname=localhost
@port=7153
@AuthenticationJWTApiHostAddress = https://{{hostname}}:{{port}}

GET {{AuthenticationJWTApiHostAddress}}/foods?query=pizza&number=5
Accept: application/json

###
GET {{AuthenticationJWTApiHostAddress}}/foods?query=pizza&number=1
Accept: application/json

###
GET {{AuthenticationJWTApiHostAddress}}/foods?query=pizza&number=100
Accept: application/json

###
GET {{AuthenticationJWTApiHostAddress}}/foods?query=burger&number=20
Accept: application/json